
#include<stdio.h>

void main(){

	int x = 10;
	int i =1;
	fordemo:
		printf("printing......\n");
	for(;i <= x;){

		i++;
		goto fordemo;
	}
	printf("After for loop\n");
}
/*
shital@sarode:~/Desktop/PPA/Daily Codes/Daily Codes-17July 2020(goto statement)$ cc gotostatement2.c
shital@sarode:~/Desktop/PPA/Daily Codes/Daily Codes-17July 2020(goto statement)$ ./a.out 
printing......
printing......
printing......
printing......
printing......
printing......
printing......
printing......
printing......
printing......
printing......
After for loop
*/
